<% [338, 300, 326, 318, 305, 337, 308, 322, 325, 339].each do |i| %>
  configuration_token_<%= i %>:
    expires_at: <%= DateTime.now + 21.days %>
    value: aBc<%= i %>XyZ
    entity_id: <%= ActiveRecord::FixtureSet.identify(:"participant#{i}") %>
<% end %>
