AllCops:
  Exclude:
    - bin/**
    - config/**
    - db/**
    - app/helpers/**

Documentation:
  Exclude:
    - spec/**

DotPosition:
  Enabled: false

FinalNewline:
  Enabled: false

HandleExceptions:
  Enabled: false

IfUnlessModifier:
  Enabled: false

LineLength:
  Exclude:
    - spec/**

StringLiterals:
  EnforcedStyle: double_quotes

WordArray:
  Enabled: false