inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

Documentation:
  Exclude:
    - spec/**/*

LambdaCall:
  Enabled: false

NumericLiterals:
  Enabled: false

SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

StringLiterals:
  EnforcedStyle: double_quotes
