language: ruby
cache: bundler
rvm:
- 2.3.0
gemfile:
- Gemfile
- gemfiles/Gemfile.rails-5.0-beta
before_script:
- bundle exec rake db:create db:migrate
sudo: false
notifications:
  slack:
    secure: d8633iBtJG+A+GN+hK6Z0soaKrA+FdpvqW9K3pbU+fvUzH28hedF/UxTxkqxL/Kts7WDwycWVRIwm1EBcUmncKH+zXG6TZ0HuL59rt2l91ktrXmAHFqU2DhdkSrGak8HAQjuHMO0UdXLU0ONYXJiZKs/n1nb5z5n8S6yXddqGZc=
