# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3937c4da11b4c63e1c3315fd7b5c5fab270324f4b71812abd29e3f6cbdf0f8bf5e132018adc5ddfb5c7fd34c8a83abcfed729d54c5ff8507cc444fe1a1c94611

test:
  secret_key_base: 1e121690137f1d9845da345781f5db41924d1cfe770f89fd865eba8db811ac58bc0d744b4da222784e4d079e1ed199315064c2f120b736c385fd18183e62b201

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
